name: projectjen
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.1
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  confetti: ^0.7.0
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  hidden_drawer_menu: ^3.0.1
  slide_to_act: ^2.0.1
  file_picker: ^5.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/main.png
    - assets/images/top1.png
    - assets/images/top2.png
    - assets/images/bottom1.png
    - assets/images/bottom2.png
    - assets/images/google-plus.png
    - assets/images/facebook.png
